// action types for redux

export const HYPOTHERMIA_ALERT = "HYPOTHERMIA_ALERT"

export const TRUE = "TRUE"

export const FALSE = "FALSE" 
//map types
export const SET_POPUP_FOCUS = "SET_POPUP_FOCUS"
export const CLEAR_POPUP_FOCUS = "CLEAR_POPUP_FOCUS"

// health action types
export const SET_CHILD_MENTAL_HEALTH_PROVIDERS = "SET_CHILD_MENTAL_HEALTH_PROVIDERS"
export const SET_ADULT_MENTAL_HEALTH_PROVIDERS = "SET_ADULT_MENTAL_HEALTH_PROVIDERS"
export const SET_PRIMARY_CARE_CENTERS = "SET_PRIMARY_CARE_CENTERS"
export const SET_HOSPITALS = "SET_HOSPITALS"
export const SET_PHARMACIES = "SET_PHARMACIES"
export const SET_DIALYSIS_CLINICS = "SET_DIALYSIS_CLINICS"
export const SET_HIV_CLINICS = "SET_HIV_CLINICS"
export const SET_YOUTH_REHAB_FACILITIES = "SET_YOUTH_REHAB_FACILITIES"
export const SET_OPIOID_TREATMENT_FACILITIES = "SET_OPIOID_TREATMENT_FACILITIES"

// food action types 
export const SET_JOYFUL_FOOD_MARKETS = "SET_JOYFUL_FOOD_MARKETS"
export const SET_HEALTHY_CORNER_STORES = "SET_HEALTHY_CORNER_STORES"
export const SET_WIC_MARKETS = "SET_WIC_MARKETS"

// safety action types
export const SET_HOMELESS_SHELTER_LOCATIONS = "SET_HOMELESS_SHELTER_LOCATIONS"

//service action types
export const SET_SERVICES = "SET_SERVICES"
export const SET_SERVICE_TARGETS_DROPDOWN = "SET_SERVICE_TARGETS_DROPDOWN"
export const SET_SELECTED_SERVICE_TARGET = "SET_SELECTED_SERVICE_TARGET"
export const TOGGLE_OR_AND ="TOGGLE_OR_AND"
export const ADD_REMOVE_FROM_FILTER = "ADD_REMOVE_FROM_FILTER"
export const ADD_TO_FILTER = "ADD_TO_FILTER"
export const REMOVE_FROM_FILTER = "REMOVE_FROM_FILTER"
export const CLEAR_SERVICE_FILTER = "CLEAR_SERVICE_FILTER"

//service top menue 
// export const FOOD_GROCERIES = "FOOD_GROCERIES"
// export const HOUSING = "HOUSING"
// export const MEALS = "MEALS"
// export const OPEN_TO_PUBLIC = "OPEN_TO_PUBLIC"
// export const PUBLIC_RESTROOMS = "PUBLIC_RESTROOMS"
// export const REFRESHMENTS = "REFRESHMENTS"


// FOOD_GROCERIES(pin):null
// HOUSING(pin):null
// MEALS(pin):null
// OPEN_TO_PUBLIC(pin):null
// PUBLIC_RESTROOMS(pin):"Yes"
// REFRESHMENTS(pin):null
// SHOWERS(pin):null
// TARGET(pin):"Men & Women"
// TANF Temporary Assistance for Needy Families
// TANF_FINANCIAL_ASSISTANCE(pin):null