// action types for redux

export const HYPOTHERMIA_ALERT = "HYPOTHERMIA_ALERT"

export const TRUE = "TRUE"

export const FALSE = "FALSE" 


// health action types
export const SET_CHILD_MENTAL_HEALTH_PROVIDERS = "SET_CHILD_MENTAL_HEALTH_PROVIDERS"
export const SET_ADULT_MENTAL_HEALTH_PROVIDERS = "SET_ADULT_MENTAL_HEALTH_PROVIDERS"
export const SET_DIALYSIS_CLINICS = "SET_DIALYSIS_CLINICS"
export const SET_PRIMARY_CARE_CENTERS = "SET_PRIMARY_CARE_CENTERS"
export const SET_HOSPITALS = "SET_HOSPITALS"