// action types for redux

export const HYPOTHERMIA_ALERT = "HYPOTHERMIA_ALERT"

export const TRUE = "TRUE"

export const FALSE = "FALSE" 


// health action types
export const SET_CHILD_MENTAL_HEALTH_PROVIDERS = "SET_CHILD_MENTAL_HEALTH_PROVIDERS"
export const SET_ADULT_MENTAL_HEALTH_PROVIDERS = "SET_ADULT_MENTAL_HEALTH_PROVIDERS"
export const SET_PRIMARY_CARE_CENTERS = "SET_PRIMARY_CARE_CENTERS"
export const SET_HOSPITALS = "SET_HOSPITALS"
export const SET_PHARMACIES = "SET_PHARMACIES"
export const SET_DIALYSIS_CLINICS = "SET_DIALYSIS_CLINICS"
export const SET_HIV_CLINICS = "SET_HIV_CLINICS"
export const SET_YOUTH_REHAB_FACILITIES = "SET_YOUTH_REHAB_FACILITIES"
export const SET_OPIOID_TREATMENT_FACILITIES = "SET_OPIOID_TREATMENT_FACILITIES"

// food action types 
export const SET_JOYFUL_FOOD_MARKETS = "SET_JOYFUL_FOOD_MARKETS"
export const SET_HEALTHY_CORNER_STORES = "SET_HEALTHY_CORNER_STORES"
export const SET_WIC_MARKETS = "SET_WIC_MARKETS"